# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9410d94451c87c96361a930f4f36224622a3bc70c51a4e30081216dddebeaeb0175dedd79b749021c83225e6a6fb972326c719c603a0a227dafe93cc89f71477

test:
  secret_key_base: 2adfaa0b38ed66e391f846fe88f76754ea64334ad08f2034f20c2852c8d2e9783268f78c252ae4c0c6e0234a1402849548503b4569b7605b3927bab1302fa8f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
